### ISSUE TITLE
datasets and environment setup

### ISSUE THREAD

**Issue by lapetite123** [ken012git/joint_point_based#1]
I am interested in your amazing work and want to run your code. Do I need to  download the whole scannetv2 datasets? and can you please tell the exact environment setup? thanks very much!

**Comment by liu115** [comment]
Yes, you have to download the whole scannetv2 dataset which includes the mesh files (.ply) and the scans files (camera parameters) for each scene. For the instruction to extract the scene scans, you can follow https://github.com/ScanNet/ScanNet

**Comment by RichardTaoK** [comment]
Thanks for your amazing work,but when i deal with the data ,i cannot understand the role of prepare_data/render.and i also don't know how to run it,can you describe it in more detail???thanks very much!

**Comment by liu115** [comment]
`prepare_data/render` is used to prepare rendered 2D image and labels from the scene model given by ScanNet. We need them for the 2D stream in our model.

For the usage, please follow the [README ](https://github.com/ken012git/joint_point_based/blob/master/prepare_data/render/README.md) in `prepare_data/render` .

**Comment by RichardTaoK** [comment]
@liu115  thank you for your explanation
i still have some questions,the paper mentioned that you back-project each pixel from the image coordinate to the 3D world coordinate with camera paprameter,but i only find barycentric interpolation ,i could not find fnd the code for using camera paremeters,can you explain how it works,and make the 3D coordinate have the corresponding 256-dimensional features?

**Comment by hyc-xyz** [comment]
> @liu115 thank you for your explanation
> i still have some questions,the paper mentioned that you back-project each pixel from the image coordinate to the 3D world coordinate with camera paprameter,but i only find barycentric interpolation ,i could not find fnd the code for using camera paremeters,can you explain how it works,and make the 3D coordinate have the corresponding 256-dimensional features?

I think what you are finding is this [line](https://github.com/ken012git/joint_point_based/blob/master/prepare_data/render/render_scene/sfm_pose.cpp#L155)
This code reads the camera pose from ScanNet Dataset v2 and renders the images from the ply files.

Thank you for finding our work and paper useful. 
Hopes they help you.

**Comment by ken012git** [comment]
I think what you are finding is this [line](https://github.com/ken012git/joint_point_based/blob/master/prepare_data/render/render_scene/sfm_pose.cpp#L155) in `prepare_data/render/render_scene/sfm_pose.cpp`
This code reads the camera pose from ScanNet Dataset v2 and renders the images from the ply files.

Thank you for finding our work and paper useful.
Hopes they help you.

**Comment by RichardTaoK** [comment]
Thank you for your reply.But i still sorry for not running the render code successfully.
I follw the 'READEME' in 'render',I've never been able to install the OpenImageIO.There are many bug in OpenImage/IO，I'm new in pointcloud,but i really need the processed data set in my expermients.can you help me?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hychiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 晚上10:19
收件人:&nbsp;"ken012git/joint_point_based"<joint_point_based@noreply.github.com&gt;;
抄送:&nbsp;"w"<2579312470@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ken012git/joint_point_based] datasets and environment setup (#1)




I think what you are finding is this line in prepare_data/render/render_scene/sfm_pose.cpp
 This code reads the camera pose from ScanNet Dataset v2 and renders the images from the ply files.
 
Thank you for finding our work and paper useful.
 Hopes they help you.

**Comment by hyc-xyz** [comment]
> Thank you for your reply.But i still sorry for not running the render code successfully. I follw the 'READEME' in 'render',I've never been able to install the OpenImageIO.There are many bug in OpenImage/IO，I'm new in pointcloud,but i really need the processed data set in my expermients.can you help me?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hychiang"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月4日(星期三) 晚上10:19 收件人:&nbsp;"ken012git/joint_point_based"<joint_point_based@noreply.github.com&gt;; 抄送:&nbsp;"w"<2579312470@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [ken012git/joint_point_based] datasets and environment setup (#1) I think what you are finding is this line in prepare_data/render/render_scene/sfm_pose.cpp This code reads the camera pose from ScanNet Dataset v2 and renders the images from the ply files. Thank you for finding our work and paper useful. Hopes they help you. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


Which code are you running? and what error message did you get?
Would you give us more clues that we could help with?

**Comment by ken012git** [comment]
Which code are you running? and what error message did you get?
Would you give us more clues that we could help with?

**Comment by RichardTaoK** [comment]
when i run 'make syn_pose',i met the error "can't find -lOpenImageIO", i find it in MAkefile,so i try to install openImageIO,but i can't install it sucessfully





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hychiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 中午12:10
收件人:&nbsp;"ken012git/joint_point_based"<joint_point_based@noreply.github.com&gt;;
抄送:&nbsp;"w"<2579312470@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ken012git/joint_point_based] datasets and environment setup (#1)




Which code are you running? and what error message did you get?
 Would you give us more clues that we could help with?

**Comment by ken012git** [comment]
I think we are no longer using the OIIO lib, but we forget to remove the flag in our makefile.
Would you please try to remove the flag and compile it again?

Also please set your Eigen path and your inlcude and library path on our system
```
EIGEN_INC=/path/to/eigen
INC=/usr/local/include
LIB=/usr/local/lib
```

**Comment by RichardTaoK** [comment]
I'm very sorry to bother you.But after trying the new commit ,i still met the error
`g++ -Wall -O2 -std=c++14 syn_pose.o render.o tinyply.o -o syn_pose -L /home/user/anaconda3/envs/hmt/lib -fopenmp -lpthread -lz -lopenblas -llapack
render.o：在函数‘OpenImageIO_v2_1::ImageSpec::~ImageSpec()’中：
render.cpp:(.text._ZN16OpenImageIO_v2_19ImageSpecD2Ev[_ZN16OpenImageIO_v2_19ImageSpecD5Ev]+0x28)：对‘OpenImageIO_v2_1::ParamValue::clear_value()’未定义的引用
render.o：在函数‘xt::dump_image_options::dump_image_options()’中：
render.cpp:(.text._ZN2xt18dump_image_optionsC2Ev[_ZN2xt18dump_image_optionsC5Ev]+0x41)：对‘OpenImageIO_v2_1::ImageSpec::ImageSpec(int, int, int, OpenImageIO_v2_1::TypeDesc)’未定义的引用
render.cpp:(.text._ZN2xt18dump_image_optionsC2Ev[_ZN2xt18dump_image_optionsC5Ev]+0x95)：对‘OpenImageIO_v2_1::ImageSpec::attribute(OpenImageIO_v2_1::string_view, OpenImageIO_v2_1::TypeDesc, void const*)’未定义的引用
render.o：在函数‘void xt::dump_image<xt::xarray_container<xt::uvector<unsigned char, std::allocator<unsigned char> >, (xt::layout_type)1, xt::svector<unsigned long, 4ul, std::allocator<unsigned long>, true>, xt::xtensor_expression_tag> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xt::xexpression<xt::xarray_container<xt::uvector<unsigned char, std::allocator<unsigned char> >, (xt::layout_type)1, xt::svector<unsigned long, 4ul, std::allocator<unsigned long>, true>, xt::xtensor_expression_tag> > const&, xt::dump_image_options const&)’中：
render.cpp:(.text._ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE[_ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE]+0x1d7)：对‘OpenImageIO_v2_1::ImageOutput::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
render.cpp:(.text._ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE[_ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE]+0x616)：对‘OpenImageIO_v2_1::ParamValue::init_noclear(OpenImageIO_v2_1::ustring, OpenImageIO_v2_1::TypeDesc, int, OpenImageIO_v2_1::ParamValue::Interp, void const*, bool)’未定义的引用
render.cpp:(.text._ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE[_ZN2xt10dump_imageINS_16xarray_containerINS_7uvectorIhSaIhEEELNS_11layout_typeE1ENS_7svectorImLm4ESaImELb1EEENS_22xtensor_expression_tagEEEEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11xexpressionIT_EERKNS_18dump_image_optionsE]+0xe70)：对‘OpenImageIO_v2_1::ParamValue::clear_value()’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'syn_pose' failed
make: *** [syn_pose] Error 1
`
and i have installed the OpenImageIO,i still met the same error.
This mistake is driving me crazy.

**Comment by hychiang-git** [comment]
I am very sorry our program could not function.

We rely on [xtensor-io](https://xtensor-io.readthedocs.io/en/latest/installation.html) to dump our buffers in `npy` format. We did this because we want to render the xyz map in order to keep track of each pixel's 3D coordinate and feed them into our python learning parts.

And I just found [xtensor-io](https://xtensor-io.readthedocs.io/en/latest/installation.html) depends on [OIIO](https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md). If you still want to run our program, please install OIIO and link it correctly. (sorry)

Would you check if there is OIIO's header under `/usr/local/include` and library under `/usr/local/lib` after you `sudo apt-get install libopenimageio-dev` ?

The other option is to [build OIIO](https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md) yourself, and this was what we did at the time.

**Comment by RichardTaoK** [comment]
Thank you for your patient reply. I have solved theproblem according to your instructions.By the way,`-lOpenImageIO`  need to be added in Makefile.
Thanks again for your patience.
