### ISSUE TITLE
about project 2d image to 3d space

### ISSUE THREAD

**Issue by bonbonjour** [ken012git/joint_point_based#3]
hello, I noticed that your code includes projecting 2d image feature to 3d mesh,  can  i use your projection code to project 2d image feature to raw point cloud?

**Comment by twn29004** [comment]
hello, Can you tell me where the code is ? plz

**Comment by hychiang-git** [comment]
> hello, I noticed that your code includes projecting 2d image feature to 3d mesh, can i use your projection code to project 2d image feature to raw point cloud?

I am sorry for the late reply. The code was done at [render.cpp line 187](https://github.com/ken012git/joint_point_based/blob/master/prepare_data/render/render_scene/render.cpp#L187) written in cpp. You may also check the details in our [paper](https://arxiv.org/pdf/1908.00478.pdf) section 3.1. Image Features to 3D Vertices.
