### ISSUE TITLE
where is the code to project image feature to 3d space

### ISSUE THREAD

**Issue by lapetite123** [ken012git/joint_point_based#4]
Hello, can you please tell me where is the code to project image feature to 3d space, cause i didn't find it. thanks!

**Comment by twn29004** [comment]
I want to know it too. Have you find it?

**Comment by hychiang-git** [comment]
see Issue https://github.com/ken012git/joint_point_based/issues/3

**Comment by twn29004** [comment]
> see Issue #3

thank you for your reply
